[package]
name = "rusp"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.168"
rand = "0.8.5"
rand_core = "0.6.4"
rand_pcg = "0.3.1"
rayon = "1.10.0"

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
strip = "debuginfo"
overflow-checks = true
panic = "abort"
