#target at termux googple pixel 7a
[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-C",
    "debuginfo=0",
    "-C",
    "strip=debuginfo",
    "-C",
    "target-cpu=cortex-x1",
    "-Z",
    "tune-cpu=cortex-x1",
    "-C",
    "link-arg=-z",
    "-C",
    "link-arg=max-page-size=4096",
    "-C",
    "link-arg=-z",
    "-C",
    "link-arg=common-page-size=64",
    "-C",
    "link-arg=-z",
    "-C",
    "link-arg=align-tls-segment=64",
    "-C",
    "target-feature=+crt-static",
]
linker = "aarch64-linux-gnu-gcc"

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C",
    "debuginfo=0",
    "-C",
    "strip=debuginfo",
    "-C",
    "target-cpu=native",
    "-Z",
    "tune-cpu=native",
]
linker = "link.exe"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "debuginfo=0", "-C", "strip=debuginfo"]
linker = "gcc"

[build]
# Set the default target to aarch64-unknown-linux-gnu
target = "aarch64-unknown-linux-gnu"
